modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/HoneyBerries/PingPlayer"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/HoneyBerries/PingPlayer"
logoFile="assets/player-ping/icon.png"
authors="${mod_authors}"
displayTest="IGNORE_SERVER_VERSION"
description='''${mod_description}'''

[[mixins]]
config="player-ping.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
